# -*- coding: utf-8 -*-
"""011201133_Syed Eftasum Alam_AILab(E)_KMeans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1erzx9zm0erYKpKEuFU4CKbnnAw2GPqaj
"""

from google.colab import files
upload = files.upload()

import matplotlib.pyplot as plt
import numpy as np
X = np.loadtxt("jain_feats.txt")
centroid_old = np.loadtxt("jain_centers.txt")
centroid_new = np.zeros((2, 2))

#display(X)
#display(centroid_old)

plt.scatter(X[:,0],X[:,1], color='blue',s=5)
plt.scatter(centroid_old[:, 0], centroid_old[:, 1], color='orange', marker='*', s=200 )
plt.show()

for e in range(1000):
  label = np.zeros(len(X))
  for i in range(len(X)):
    distance = np.zeros(len(centroid_old))
    for j in range(len(centroid_old)):
      distance[j] = np.sqrt(np.sum((X[i,:] - centroid_old[j,:])**2))
    label[i] = np.argmin(distance)
  #Update:
  centroid_new[0] = np.mean(X[label == 0], axis=0)
  centroid_new[1] = np.mean(X[label == 1], axis=0)

  #exit:
  for j in range(len(centroid_new)):
    difference = centroid_new[j] - centroid_old[j]

    if np.max(difference) < 1E-7:
        break
    else:
        centroid_old = centroid_new

label1 = X[label==0]
label2 = X[label==1]

plt.scatter(label1[:,0], label1[:,1], color='red', s = 5)
plt.scatter(label2[:,0], label2[:,1], color='green' , s = 5)
plt.scatter(centroid_old[:,0], centroid_old[:,1], marker='*', color=['red','green'], s=200)
plt.show()